#!/usr/bin/env bash
#script that display "To infinity and Beyond" indefinitely with sleep 2 in between each iteration

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
